apiVersion: v1
kind: ServiceAccount
metadata:
  name: muhammed-sa
  namespace: muhammed-dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muhammed-rb
  namespace: muhammed-dev
subjects:
  - kind: ServiceAccount
    name: muhammed-sa
    namespace: muhammed-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
