apiVersion: v1
kind: ServiceAccount
metadata:
  name: arthur-sa
  namespace: arthur-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arthur-rb
  namespace: arthur-dev
subjects:
  - kind: ServiceAccount
    name: arthur-sa
    namespace: arthur-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
